using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TodoApi.Models
{
    public class TodoItem
    {
        // The Id is a Guid automatically generated by the database
        public string Id { get; set; }
        public string Content { get; set; }
        public bool Done { get; set; }
        public string UserForeignKey { get; set; }
    }
}
